# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Run Go Script Daily

on:
  schedule:
    - cron: '43 3 * * 1-5'  

jobs:
  run-go-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3' 

    - name: Run Go script
      run: go run main.go
